CREATE DATABASE study;

DROP TABLE EMPLOYEES;

CREATE TABLE EMPLOYEES(
NAME VARCHAR(50),
ID INTEGER,
SALARY NUMERIC,
BRANCH_ID INTEGER
);

SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES (ID, NAME, SALARY, BRANCH_ID) VALUES (4603, 'Alayna', 180, 15);
INSERT INTO EMPLOYEES (ID, NAME, SALARY, BRANCH_ID) VALUES (4651, 'Juliet', 300, 17);
INSERT INTO EMPLOYEES (ID, NAME, SALARY, BRANCH_ID) VALUES (864, 'Holly', 330, 16);
INSERT INTO EMPLOYEES (ID, NAME, SALARY, BRANCH_ID) VALUES (2842, 'Kyra', 280, 16);

SELECT BRANCH_ID, SUM(SALARY) AS TOTAL FROM EMPLOYEES GROUP BY BRANCH_ID ORDER BY BRANCH_ID asc;